/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2019-01-24 01:04:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.template;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xnx3.j2ee.Global;
import com.xnx3.wangmarket.admin.G;

public final class templatePlugin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1430113524000L));
    _jspx_dependants.put("/WEB-INF/lib/xnx3_tld.jar", Long.valueOf(1512734430000L));
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/xnx3_tld.jar!/META-INF/xnx3.tld", Long.valueOf(1495004768000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.xnx3.j2ee.Global");
    _jspx_imports_classes.add("com.xnx3.wangmarket.admin.G");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../iw/common/head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("浏览模版插件", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"http://res.weiunity.com/css/layerGlobal.css\" media=\"all\">\n");
      out.write("\n");
      out.write("<!-- author:管雷鸣 -->\n");
      out.write("<style>\n");
      out.write(".list{\n");
      out.write("\tpadding-left: 50px;\n");
      out.write("}\n");
      out.write(".list>div{\n");
      out.write("\tfloat:left;\n");
      out.write("\twidth:48%;\n");
      out.write("\tpadding:0.5%;\n");
      out.write("\tmin-width: 500px;\n");
      out.write("    max-width: 900px;\n");
      out.write("}\n");
      out.write(".list>div>div{\n");
      out.write("\tpadding-bottom: 35px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/*预览图*/\n");
      out.write(".previewImg{\n");
      out.write("\twidth:100%;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("/*预览按钮*/\n");
      out.write(".previewButton{\n");
      out.write("\tmargin-top: -30px;\n");
      out.write("\ttext-align: right;\n");
      out.write("\toverflow-x: hidden;\n");
      out.write("}\n");
      out.write(".previewButton a{\n");
      out.write("    background-color: #FF5722;\n");
      out.write("    border-radius: 15px;\n");
      out.write("    padding: 3px;\n");
      out.write("    padding-left: 12px;\n");
      out.write("    padding-right: 22px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    color: #eeeeee;\n");
      out.write("    font-size: 18px;\n");
      out.write("    margin-right: -12px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/*模版名字，编号*/\n");
      out.write(".templateName{\n");
      out.write("\twidth:100%;\n");
      out.write("\ttext-align:center;\n");
      out.write("\tcolor:#2F4056;\n");
      out.write("\tpadding-top: 8px;\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("/*模版简介说明*/\n");
      out.write(".info{\n");
      out.write("\tcolor:#c2c2c2;\n");
      out.write("\tpadding: 10px;\n");
      out.write("\tpadding-bottom: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".leftImage{\n");
      out.write("\tfloat:left;\n");
      out.write("\twidth: 50%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* 使用说明 */\n");
      out.write(".usedoc{\n");
      out.write("\tpadding-left: 10px;\n");
      out.write("    text-align: right;\n");
      out.write("    padding-right: 10px;\n");
      out.write("}\n");
      out.write(".usedoc a{\n");
      out.write("\tcolor: blue;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"site-title\">\n");
      out.write("\t<fieldset><legend><a name=\"fieldset\">云端插件列表</a></legend></fieldset>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"list\" id=\"cloudList\">\n");
      out.write("\t加载中...\n");
      out.write("\n");
      out.write("\t\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("layui.use('element', function(){\n");
      out.write("\tvar element = layui.element;\n");
      out.write("});\n");
      out.write("\n");
      out.write("//使用某个云端模版，传入其模版名、编号 templateName\n");
      out.write("function useTemplatePlugin(pluginName){\n");
      out.write("\tvar dtp_confirm = layer.confirm('确定要导入模版插件：'+pluginName+'?', {\n");
      out.write("\t  btn: ['立即导入','取消'] //按钮\n");
      out.write("\t}, function(){\n");
      out.write("\t\tlayer.close(dtp_confirm);\n");
      out.write("\t\tiw.loading(\"获取中\");\n");
      out.write("\t\t$.post('");
      out.print(basePath );
      out.write("template/restoreTemplatePluginByRemote.do?pluginName='+pluginName, function(data){\n");
      out.write("\t\t\tiw.loadClose();\n");
      out.write("\t\t\tif(data.result == '1'){\n");
      out.write("\t\t\t\ttemplateComparePreview();\n");
      out.write("\t\t \t}else if(data.result == '0'){\n");
      out.write("\t\t \t\tparent.iw.msgFailure(data.info);\n");
      out.write("\t\t \t}else{\n");
      out.write("\t\t \t\tparent.iw.msgFailure();\n");
      out.write("\t\t \t}\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t}, function(){\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("//弹出模版比对窗口，选择要还原的项\n");
      out.write("//url:  相对路径，比如 template/restoreTemplateByRemote.do\n");
      out.write("function templateComparePreview(){\n");
      out.write("\tlayer.open({\n");
      out.write("\t\ttype: 2, \n");
      out.write("\t\ttitle:'导入模版插件', \n");
      out.write("\t\tarea: ['800px', '560px'],\n");
      out.write("\t\tshadeClose: true, //开启遮罩关闭\n");
      out.write("\t\tcontent: '");
      out.print(basePath );
      out.write("template/restoreTemplateComparePreview.do'\n");
      out.write("\t});\n");
      out.write("}\n");
      out.write("\n");
      out.write("//加载云端的模版列表\n");
      out.write("function loadCloudTemplateList(){\n");
      out.write("\t//若使用云端模版库，则可以将下面请求地址换为 http://wang.market/cloudTemplateList.do\n");
      out.write("\t$.getJSON('http://res.weiunity.com/cloudControl/templatePlugin.json',function(obj){\n");
      out.write("\t\tvar html = '';\t//云端模版的列表\n");
      out.write("\t\t\tif(obj.result == '1'){\n");
      out.write("\t\t\t\tvar divArray = new Array();\t//共分2列，也就是下标为0～1\n");
      out.write("\t\t\t\tfor(var i=0; i<obj.list.length; i++){\n");
      out.write("\t\t\t\t\tvar xiabiao = i%2;\t//取余，得数组下表\n");
      out.write("\t\t\t\t\tvar to = obj.list[i];\n");
      out.write("\t\t\t\t\tvar temp = '<div><div class=\"leftImage\"><img src=\"http://res.weiunity.com/template_plugin/'+to.name+'/preview.jpg\" class=\"previewImg\" onclick=\"useTemplatePlugin(\\''+to.name+'\\');\"><div class=\"previewButton\"><a href=\"'+to.demoUrl+'\" target=\"_black\">点此预览</a></div></div><div class=\"leftImage\"><div class=\"templateName\" onclick=\"useTemplatePlugin(\\''+to.name+'\\');\">'+to.title+'</div><div class=\"info\">'+to.info+'</div><div class=\"usedoc\"><a href=\"'+to.docUrl+'?MASTER_SITE_URL=");
      out.print(Global.get("MASTER_SITE_URL") );
      out.write("\" target=\"_black\">使用说明</a></div></div></div>';\n");
      out.write("\t\t\t\t\t/* var temp = '<div>'+\n");
      out.write("\t\t\t\t\t\t\t\t'<img src=\"http://res.weiunity.com/template/'+to.name+'/preview.jpg\" class=\"previewImg\" onclick=\"useCloudTemplate(\\''+to.name+'\\');\" />'+\n");
      out.write("\t\t\t\t\t\t\t\t'<div class=\"previewButton\"><a href=\"http://'+to.name+'.wscso.com\" target=\"_black\">点此预览</a></div>'+\n");
      out.write("\t\t\t\t\t\t\t\t'<div class=\"templateName\" onclick=\"useCloudTemplate(\\''+to.name+'\\');\">模版编号：'+to.name+'</div>'+\n");
      out.write("\t\t\t\t\t\t\t\t'<div class=\"info\">'+to.intro+'</div>'+\n");
      out.write("\t\t\t\t\t \t \t\t'</div>';\n");
      out.write("\t\t\t\t\t*/ \t\t\n");
      out.write("\t\t\t\t\tif(divArray[xiabiao] == null){\n");
      out.write("\t\t\t\t\t\tdivArray[xiabiao] = '';\n");
      out.write("\t\t\t\t\t}\t \t\t\n");
      out.write("\t\t\t\t\tdivArray[xiabiao] = divArray[xiabiao] + temp;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t//将四个div分别遍历，组合成显示的html\n");
      out.write("\t\t\t\tfor(var i=0; i<divArray.length; i++){\n");
      out.write("\t\t\t\t\thtml = html + '<div>' + divArray[i] +'</div>';\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tdocument.getElementById(\"cloudList\").innerHTML = html;\n");
      out.write("\t     \t}else if(obj.result == '0'){\n");
      out.write("\t     \t\t $.toast(obj.info, \"cancel\", function(toast) {});\n");
      out.write("\t     \t}else{\n");
      out.write("\t     \t\talert(obj.result);\n");
      out.write("\t     \t}\n");
      out.write("\t\t});\n");
      out.write("}\n");
      out.write("loadCloudTemplateList();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
