/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2019-01-24 01:06:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.plugin.templateDevelop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xnx3.wangmarket.admin.G;
import com.xnx3.j2ee.entity.User;
import com.xnx3.j2ee.Global;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/shiro-web-1.2.3.jar", Long.valueOf(1430113542000L));
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/shiro-web-1.2.3.jar!/META-INF/shiro.tld", Long.valueOf(1393323284000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1430113524000L));
    _jspx_dependants.put("/WEB-INF/lib/xnx3_tld.jar", Long.valueOf(1512734430000L));
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/xnx3_tld.jar!/META-INF/xnx3.tld", Long.valueOf(1495004768000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.xnx3.j2ee.Global");
    _jspx_imports_classes.add("com.xnx3.j2ee.entity.User");
    _jspx_imports_classes.add("com.xnx3.wangmarket.admin.G");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../iw/common/head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("管理后台", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("<script src=\"http://res.weiunity.com/js/fun.js\"></script>\n");
      out.write("<script>\n");
      out.write("var masterSiteUrl = '");
      out.print(Global.get("MASTER_SITE_URL") );
      out.write("'; \n");
      out.write("</script>\n");
      out.write("<script src=\"");
      out.print(basePath );
      out.write("js/admin/commonedit.js?v=");
      out.print(G.VERSION );
      out.write("\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".explain{\n");
      out.write("\tfont-size:14px;\n");
      out.write("\tcolor:gray;\n");
      out.write("\tpadding-left: 50px;\n");
      out.write("\tpadding-top:15px;\n");
      out.write("}\n");
      out.write("#dev_cont .explain ul li{\n");
      out.write("\tlist-style: decimal;\n");
      out.write("}\n");
      out.write("#dev_cont .buzhoutitle{\n");
      out.write("\tpadding-top:20px;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("    font-weight: 500;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<div style=\"margin:0 auto;\">\n");
      out.write("\t\n");
      out.write("\t<div id=\"dev_cont\" style=\"padding: 20px;\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"buzhoutitle\">前言</div>\n");
      out.write("\t\t\t<div class=\"explain\">\n");
      out.write("\t\t\t\t注意：\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li>此插件仅限于模版开发人员使用</li>\n");
      out.write("\t\t\t\t\t<li>如果你是Windows系统，请不要将项目此放到C盘，否则可能会由于权限等问题导致无法创建相关文件夹。</li>\n");
      out.write("\t\t\t\t\t<li>不要将本项目放到有空格、中文字符的文件夹（路径）中</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"buzhoutitle\">第一步：给要新建立的模版起一个编码</div>\n");
      out.write("\t\t\t<div class=\"layui-form-item\" style=\" padding-left: 40px;padding-top: 15px; margin-bottom: 0px;\">\n");
      out.write("\t\t\t    <div class=\"layui-input-inline\">\n");
      out.write("\t\t\t      <input type=\"text\" name=\"templateName\" id=\"templateName\" placeholder=\"请输入模版编码\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.templateName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  class=\"layui-input\">\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t    <button class=\"layui-btn layui-btn-primary\" onclick=\"saveTemplateName();\">保存</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"explain\">\n");
      out.write("\t\t\t\t注意：\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li>模版编码，也就是模版的唯一标示，不可跟网市场中的其他模版的编码重名。请使用你公司名字的首字母为前缀进行命名。如公司名字为“潍坊雷鸣云网络科技有限公司”，则模版编码前缀为“wflmy”，如模版编码叫\"wflmy001\"。如果你是个人，比如名字叫“管雷鸣”，那么模版编码的前缀为名字的首字母“glm”</li>\n");
      out.write("\t\t\t\t\t<li>只限使用英文、数字</li>\n");
      out.write("\t\t\t\t\t<li>长度在20个字符以内</li>\n");
      out.write("\t\t\t\t\t<li>设置后不可更改！如果想改，你还是重新开通个网站，重新开始吧</li>\n");
      out.write("\t\t\t\t\t<li>请不要将项目此放到C盘，否则可能会由于权限等问题导致无法创建相关文件夹。</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"buzhoutitle\">第二步：打开存放模版资源的文件夹</div>\n");
      out.write("\t\t\t<div class=\"\" style=\" padding-left: 40px;padding-top: 15px;\">\n");
      out.write("\t\t\t    <div class=\"layui-input-inline\" >\n");
      out.write("\t\t\t      <div id=\"step2_path\" style=\"display:none;\">文件夹所在路径：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${exportPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.templateName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/</div>\n");
      out.write("\t\t\t      <div id=\"step2_weihuoqu\">文件夹所在路径：未获取，请先操作完第一步！</div>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"explain\">\n");
      out.write("\t\t\t\t注意：\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li>只有第一步中设置了模版编码后，这里才有这个资源文件路径。</li>\n");
      out.write("\t\t\t\t\t<li>您需要将您设计的模版中，所使用的js、css、以及图片都放到这个文件夹中</li>\n");
      out.write("\t\t\t\t\t<li>您设计的模版中，不允许使用任何来自外站的资源，只可使用这个文件夹中的资源</li>\n");
      out.write("\t\t\t\t\t<li>比如，这个文件夹中有个 css/style.css 文件，那么在模版中，可以通过 {templatePath}css/style.css 这个路径引入</li>\n");
      out.write("\t\t\t\t\t<li>css、js、images 等各种资源分好文件夹存放。禁止杂乱丢进去</li>\n");
      out.write("\t\t\t\t\t<li>资源文件所允许的后缀名为：js、xml、swf、css、png、jpg、bmp、jpeg、gif、eot、svg、ttf、woff、woff2、otf ，不在此内的后缀名将会被系统自动删除掉！</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"buzhoutitle\">第三步：开发模版</div>\n");
      out.write("\t\t\t<div class=\"\" style=\" padding-left: 40px;padding-top: 15px;\">\n");
      out.write("\t\t\t    <div class=\"layui-input-inline\" >\n");
      out.write("\t\t\t    \t<a href=\"javascript:parent.templateDevHelp();\" class=\"layui-btn layui-btn-primary\">点此查看模版开发入门示例</a>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"explain\">\n");
      out.write("\t\t\t\t注意：\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li>只有第一步中设置了模版编码后，这里才有这个资源文件路径。</li>\n");
      out.write("\t\t\t\t\t<li>您可以将您设计的模版中，所使用的js、css、以及图片都放到这个文件夹中</li>\n");
      out.write("\t\t\t\t\t<li>所有引入的绝对路径资源，必须放入第二步中所创建出来的文件夹中。在模版中引入时，必须以 {templatePath} 引入。如引入一个图片head.jpg，该图片在 第二步所创建的文件夹的images文件夹中，则这样写 &lt;img src=\"{templatePath}images/head.jpg\" /&gt;</li>\n");
      out.write("\t\t\t\t\t<li>html（模版）中请勿存在js、css代码。有关css、js方面的代码，请新建相应的js、css资源文件进行存放。（如果你不想共享出模版，只是单纯自己用，可以忽略这条）</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"buzhoutitle\">第四步：设置模版首页预览图</div>\n");
      out.write("\t\t\t<div class=\"\" style=\" padding-left: 40px;padding-top: 15px;\">\n");
      out.write("\t\t\t    <div class=\"layui-input-inline\" >\n");
      out.write("\t\t\t    \t<button type=\"button\" class=\"layui-btn layui-btn-primary\" id=\"preview_index_button\">\n");
      out.write("\t\t\t\t\t\t点此上传模版首页图片\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t    <span  id=\"stop_4_tishi\" style=\"padding-left: 50px;\">\n");
      out.write("\t\t\t    \t<a href=\"");
      out.print(basePath );
      out.write("websiteTemplate/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.templateName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/preview.jpg\"  target=\"_black\">已设置：<img id=\"stop4_img\" src=\"");
      out.print(basePath );
      out.write("websiteTemplate/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.templateName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/preview.jpg\" class=\"layui-btn layui-btn-primary\" style=\"border:0px;\" onerror=\"document.getElementById('stop_4_tishi').innerHTML = '尚未上传！请上传首页预览图片';\" /></a>\n");
      out.write("\t\t\t    </span>\n");
      out.write("\t\t\t     \n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"explain\">\n");
      out.write("\t\t\t\t注意：\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li>需要模版首页的整张图片，也就是全图。你可以使用ps自行将首页整张图做出来、也可以使用一些浏览器三方插件自动将首页截图保存出来。<a href=\"");
      out.print(basePath );
      out.write("plugin/templateDevelop/images/template_preview_demo.jpg\" target=\"_black\">点此查看图片示例</a></li>\n");
      out.write("\t\t\t\t\t<li>图片必须是jpg格式</li>\n");
      out.write("\t\t\t\t\t<li>图片大小限制在1MB以内。建议大小在 200KB ～ 500KB 之间</li>\n");
      out.write("\t\t\t\t\t<li>如果你要将此模版共享出来，这一步是必须的。如果这个模版只是你自己用，你可以不上传图片</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"buzhoutitle\">第五步：设置模版所属分类</div>\n");
      out.write("\t\t\t<div class=\"\" style=\" padding-left: 40px;padding-top: 15px;\">\n");
      out.write("\t\t\t    <div class=\"layui-input-inline layui-form\" id=\"stop_5_checkbox_item\">\n");
      out.write("\t\t\t\t\t加载中...\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"buzhoutitle\">第六步：设置模版支持的终端设备</div>\n");
      out.write("\t\t\t<div class=\"layui-form\" style=\" padding-left: 40px;padding-top: 15px;\">\n");
      out.write("\t\t\t      <div class=\"layui-form-item\">\n");
      out.write("\t\t\t\t    <label class=\"layui-form-label\">手机端</label>\n");
      out.write("\t\t\t\t    <div class=\"layui-input-block\" id=\"stop6switch_mobile\">\n");
      out.write("\t\t\t\t      <input type=\"checkbox\" name=\"switch\" lay-skin=\"switch\" lay-filter=\"client_pc\" lay-text=\"支持|不支持\">\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\t\t  <div class=\"layui-form-item\">\n");
      out.write("\t\t\t\t    <label class=\"layui-form-label\">电脑端</label>\n");
      out.write("\t\t\t\t    <div class=\"layui-input-block\" id=\"stop6switch_pc\">\n");
      out.write("\t\t\t\t      <input type=\"checkbox\" name=\"switch\" lay-skin=\"switch\" lay-text=\"支持|不支持\">\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\t\t  <div class=\"layui-form-item\">\n");
      out.write("\t\t\t\t    <label class=\"layui-form-label\">ipad</label>\n");
      out.write("\t\t\t\t    <div class=\"layui-input-block\" id=\"stop6switch_ipad\">\n");
      out.write("\t\t\t\t      <input type=\"checkbox\" name=\"switch\" lay-skin=\"switch\" lay-text=\"支持|不支持\">\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\t    <div class=\"layui-form-item\">\n");
      out.write("\t\t\t\t    <label class=\"layui-form-label\">广告展示机</label>\n");
      out.write("\t\t\t\t    <div class=\"layui-input-block\" id=\"stop6switch_display\">\n");
      out.write("\t\t\t\t      <input type=\"checkbox\" name=\"switch\" lay-skin=\"switch\" lay-text=\"支持|不支持\">\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"explain\">\n");
      out.write("\t\t\t\t注意：\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li>选择你的模版是电脑pc网站的、还是手机网站的，哪种终端用的</li>\n");
      out.write("\t\t\t\t\t<li>如果你想让模版支持多种终端，请使用响应式，用css对模版做自适应！不支持手机端单独做一个模版、电脑端再单独做一个模版。</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"buzhoutitle\">第七步：设置您的信息</div>\n");
      out.write("\t\t\t<div class=\"\" style=\" padding-left: 40px;padding-top: 15px;\">\n");
      out.write("\t\t\t    <div class=\"layui-form-item\">\n");
      out.write("\t\t\t\t    <label class=\"layui-form-label\">公司名字</label>\n");
      out.write("\t\t\t\t    <div class=\"layui-input-inline\" style=\"width: 300px;\">\n");
      out.write("\t\t\t\t      <input type=\"text\" name=\"companyname\" id=\"companyname\" placeholder=\"请输入您公司名全称\" autocomplete=\"off\" class=\"layui-input\" onchange=\"stop7InputOnchange('companyname', document.getElementById('companyname').value);\">\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t    <div class=\"layui-form-mid layui-word-aux\">如果没有可留空</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"layui-form-item\">\n");
      out.write("\t\t\t\t    <label class=\"layui-form-label\">您的姓名</label>\n");
      out.write("\t\t\t\t    <div class=\"layui-input-inline\" style=\"width: 300px;\">\n");
      out.write("\t\t\t\t      <input type=\"text\" name=\"username\" id=\"username\" placeholder=\"请输入您名字\" autocomplete=\"off\" class=\"layui-input\" onchange=\"stop7InputOnchange('username', document.getElementById('username').value);\">\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t    <div class=\"layui-form-mid layui-word-aux\">当前模版的开发者姓名</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"layui-form-item\">\n");
      out.write("\t\t\t\t    <label class=\"layui-form-label\">您的官网</label>\n");
      out.write("\t\t\t\t    <div class=\"layui-input-inline\" style=\"width: 300px;\">\n");
      out.write("\t\t\t\t      <input type=\"text\" name=\"siteurl\" id=\"siteurl\" placeholder=\"请输入您公司或您的官方网站网址\" autocomplete=\"off\" class=\"layui-input\" onchange=\"stop7InputOnchange('siteurl', document.getElementById('siteurl').value);\">\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t    <div class=\"layui-form-mid layui-word-aux\">格式如： http://www.leimingyun.com</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"font-size: 12px;color: gray;margin-top: -10px;padding-left: 110px;\">如果是公司，请输入公司官网的网址。如果是个人，可填入个人网站或者博客的网址</div>\n");
      out.write("\t\t\t    <div class=\"layui-form-item\">\n");
      out.write("\t\t\t\t    <label class=\"layui-form-label\">模版简介</label>\n");
      out.write("\t\t\t\t    <div class=\"layui-input-inline\" style=\"width: 300px;\">\n");
      out.write("\t\t\t\t      <textarea name=\"remark\" placeholder=\"请输入模版简介，可不填写\" class=\"layui-textarea\" id=\"remark\" onchange=\"stop7InputOnchange('remark', document.getElementById('remark').value);\"></textarea>\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t    <div class=\"layui-form-mid layui-word-aux\">\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"font-size: 12px;color: gray;margin-top: -10px;padding-left: 110px;\">\n");
      out.write("\t\t\t\t\t模版的简介，如模版是适用于展示机，可在此备注上，展示机显示的尺寸是1920*1680的\n");
      out.write("\t\t\t\t    \t<br/>注意，长度最大限制200个字符以内！\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t    \n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"explain\">\n");
      out.write("\t\t\t\t注意：\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li>填入的信息，会在模版列表中展示给用户看到。</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"buzhoutitle\">第八步：导出模版</div>\n");
      out.write("\t\t\t<div class=\"\" style=\" padding-left: 40px;padding-top: 15px;\">\n");
      out.write("\t\t\t    <div class=\"layui-input-inline\" >\n");
      out.write("\t\t\t    \t<button type=\"button\" class=\"layui-btn layui-btn-primary\" id=\"loadLocalTemplateFile\" onclick=\"exportTemplate();\">\n");
      out.write("\t\t\t\t\t\t点此导出模版\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"explain\">\n");
      out.write("\t\t\t\t注意：\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li>导出的模版会包含你的所有资源文件（如js、css、图片等）</li>\n");
      out.write("\t\t\t\t\t<li>导出的模版，可以在开通网站后，一键导入，即可快速创建一个网站！</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"buzhoutitle\">后记</div>\n");
      out.write("\t\t\t<div class=\"\" style=\" padding-left: 40px;padding-top: 15px;\">\n");
      out.write("\t\t\t    <div class=\"layui-input-inline\" >\n");
      out.write("\t\t\t    \t我们建议您将做好的模版共享给我们，来共同创建拓展网站模版！同时，您可以在模版中加入一些贵公司的信息，别人在浏览、使用的同时，也是在曝光您公司，也会为贵公司引流客户。\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"explain\">\n");
      out.write("\t\t\t\t共享模版条件：\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li>模版中不可出现抢客户拉客户的字眼，如 某某公司XX元建站</li>\n");
      out.write("\t\t\t\t\t<li>您可在网站最底部通栏，加入 技术支持：贵公司 ，同时加上自己公司主页的超链接</li>\n");
      out.write("\t\t\t\t\t<li>模版中若有友情链接，可默认带着贵公司的友情链接</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t\n");
      out.write("</div>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("//判断当前是否已经设置完第一步了，也就是是否已经有了模版编码了\n");
      out.write("if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.templateName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' != '' && '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.templateName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' != 'null'){\n");
      out.write("\t//更改步骤二中的模版显示\n");
      out.write("\tdocument.getElementById('step2_path').style.display = '';\n");
      out.write("\tdocument.getElementById('step2_weihuoqu').style.display = 'none';\n");
      out.write("\t\n");
      out.write("\t//设置第一步中的input为不可编辑\n");
      out.write("\t$('#templateName').attr(\"readonly\",true);\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"");
      out.print(basePath );
      out.write("plugin/templateDevelop/js/js.js?v=");
      out.print(G.VERSION );
      out.write("\"></script>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../iw/common/foot.jsp", out, false);
      out.write(' ');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
