/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2019-02-19 02:38:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.news;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xnx3.j2ee.Global;
import com.xnx3.wangmarket.admin.G;

public final class newsForTemplate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.xnx3.j2ee.Global");
    _jspx_imports_classes.add("com.xnx3.wangmarket.admin.G");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../iw/common/head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("文章内容", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"http://res.weiunity.com/js/fun.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("/**\n");
      out.write(" * 编辑页面的内容代码， 同文章列表页的一样，复制于此\n");
      out.write(" * 页面类型为独立页面\n");
      out.write(" * @param name TemplatePage.name要编辑的模版页面名字\n");
      out.write(" */\n");
      out.write("function editText(name){\n");
      out.write("\tif(parent.currentMode == 2){\n");
      out.write("\t\t//要将其切换回智能模式\n");
      out.write("\t\tparent.window.htmledit_mode();\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tparent.document.getElementById(\"currentTemplatePageName\").value = name;\n");
      out.write("\tparent.loadIframe();\n");
      out.write("\t\n");
      out.write("\ttry{\n");
      out.write("\t\tparent.document.getElementById(\"currentTemplateType\").innerHTML = '详情页模版';\n");
      out.write("\t\tparent.document.getElementById(\"tongyong\").style.display = '';\n");
      out.write("\t\tparent.document.getElementById(\"lanmu\").style.display = '';\n");
      out.write("\t\tparent.document.getElementById(\"fenye\").style.display = 'none';\n");
      out.write("\t\tparent.document.getElementById(\"wenzhang\").style.display = '';\n");
      out.write("\t\tparent.document.getElementById(\"dongtailanmu\").style.display = '';\n");
      out.write("\t\tparent.document.getElementById(\"xiangqingduyou\").style.display = '';\n");
      out.write("\t\tparent.document.getElementById(\"liebiaoduyou\").style.display = 'none';\n");
      out.write("\t}catch(err){}\n");
      out.write("\t\n");
      out.write("\t//parent.document.getElementById('iframe').src='http://localhost:8080/selfSite/template/getTemplatePageText.do?pageName='+name;\n");
      out.write("\tparent.layer.close(index);\n");
      out.write("}\n");
      out.write("\n");
      out.write("//判断文章所属的栏目，所属类型，若是独立页面，同时还是模板式编辑，那么直接进入模板编辑\n");
      out.write("if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == 3 && '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.editMode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == 1){\n");
      out.write("\teditText('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.templatePageViewName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("/*input输入框下面的文字说明*/\n");
      out.write(".explain{\n");
      out.write("\tfont-size: 12px;\n");
      out.write("    color: gray;\n");
      out.write("    padding-top: 3px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<form id=\"form\" method=\"post\" class=\"layui-form\" enctype=\"multipart/form-data\" style=\"padding-top:35px; margin-bottom: 10px; padding-right:35px;\">\n");
      out.write("\t<input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\t<input type=\"hidden\" name=\"cid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.cid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\t<input type=\"hidden\" name=\"type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.type }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\t\n");
      out.write("\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inputModelText }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("    \n");
      out.write("\t<div class=\"layui-form-item\" style=\"padding-top:15px; text-align:center;\">\n");
      out.write("\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t<button class=\"layui-btn\" lay-submit=\"\" lay-filter=\"demo1\" style=\"width:150px; font-size: 16px; height: 45px;line-height: 45px;\">保存</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("try{\n");
      out.write("\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.editUseTitlepic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == '1'){\n");
      out.write("\t\tdocument.getElementById('sitecolumn_editUseTitlepic').style.display='';\n");
      out.write("\t}\n");
      out.write("}catch(e){ }\n");
      out.write("try{\n");
      out.write("\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.editUseExtendPhotos}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == '1'){\n");
      out.write("\t\tdocument.getElementById('sitecolumn_editUseExtendPhotos').style.display='';\n");
      out.write("\t}\n");
      out.write("}catch(e){ }\n");
      out.write("try{\n");
      out.write("\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.editUseIntro}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == '1'){\n");
      out.write("\t\tdocument.getElementById('sitecolumn_editUseIntro').style.display='';\n");
      out.write("\t}\n");
      out.write("}catch(e){ }\n");
      out.write("try{\n");
      out.write("\tif('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.editUseText}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == '1'){\n");
      out.write("\t\tdocument.getElementById('sitecolumn_editUseText').style.display='';\n");
      out.write("\t}\n");
      out.write("}catch(e){ }\n");
      out.write("\n");
      out.write("var uploadExtendPhotos = {\n");
      out.write("\t\telem: '.uploadImagesButton' //绑定元素\n");
      out.write("\t\t,url: parent.masterSiteUrl+'site/uploadImage.do' //上传接口\n");
      out.write("\t\t,field: 'image'\n");
      out.write("\t\t,accept: 'file'\n");
      out.write("\t\t,size: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maxFileSizeKB}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\t\t,exts:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ossFileUploadImageSuffixList }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\t//可上传的文件后缀\n");
      out.write("\t\t,done: function(res){\n");
      out.write("\t\t\t//上传完毕回调\n");
      out.write("\t\t\tloadClose();\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar key = this.item[0].name;\t//拿到传递参数的key，也就是 extend.photos 中，数组某项的下表\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif(res.result == 1){\n");
      out.write("\t\t\t\ttry{\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"titlePicInput\"+key).value = res.url;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"titlePicA\"+key).href = res.url;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"titlePicImg\"+key).src = res.url;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"titlePicImg\"+key).style.display='';\t//避免新增加的文章，其titlepicImg是隐藏的\n");
      out.write("\t\t\t\t}catch(err){}\n");
      out.write("\t\t\t\tparent.iw.msgSuccess(\"上传成功\");\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\tparent.iw.msgFailure(res.info);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t,error: function(index, upload){\n");
      out.write("\t\t\t//请求异常回调\n");
      out.write("\t\t\tparent.iw.loadClose();\n");
      out.write("\t\t\tparent.iw.msgFailure();\n");
      out.write("\t\t}\n");
      out.write("\t\t,before: function(obj){ //obj参数包含的信息，跟 choose回调完全一致，可参见上文。\n");
      out.write("\t\t\tparent.iw.loading('上传中..');\n");
      out.write("\t\t}\n");
      out.write("\t};\n");
      out.write("\n");
      out.write("var upload;\n");
      out.write("layui.use('upload', function(){\n");
      out.write("\tupload = layui.upload;\n");
      out.write("\t//上传图片,封面图\n");
      out.write("\t//upload.render(uploadPic);\n");
      out.write("\tupload.render({\n");
      out.write("\t\telem: \"#uploadImagesButton\" //绑定元素\n");
      out.write("\t\t,url: parent.masterSiteUrl+'site/uploadImage.do' //上传接口\n");
      out.write("\t\t,field: 'image'\n");
      out.write("\t\t,accept: 'file'\n");
      out.write("\t\t,size: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maxFileSizeKB}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\t\t,exts:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ossFileUploadImageSuffixList }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\t//可上传的文件后缀\n");
      out.write("\t\t,done: function(res){\n");
      out.write("\t\t\t//上传完毕回调\n");
      out.write("\t\t\tloadClose();\n");
      out.write("\t\t\tif(res.result == 1){\n");
      out.write("\t\t\t\ttry{\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"titlePicInput\").value = res.url;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"titlePicA\").href = res.url;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"titlePicImg\").src = res.url;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"titlePicImg\").style.display='';\t//避免新增加的文章，其titlepicImg是隐藏的\n");
      out.write("\t\t\t\t}catch(err){}\n");
      out.write("\t\t\t\tparent.iw.msgSuccess(\"上传成功\");\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\tparent.iw.msgFailure(res.info);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t,error: function(index, upload){\n");
      out.write("\t\t\t//请求异常回调\n");
      out.write("\t\t\tparent.iw.loadClose();\n");
      out.write("\t\t\tparent.iw.msgFailure();\n");
      out.write("\t\t}\n");
      out.write("\t\t,before: function(obj){ //obj参数包含的信息，跟 choose回调完全一致，可参见上文。\n");
      out.write("\t\t\tparent.iw.loading('上传中..');\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t//上传图片,图集，v4.6扩展\n");
      out.write("\tupload.render(uploadExtendPhotos);\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("layui.use(['form', 'layedit', 'laydate'], function(){\n");
      out.write("  var form = layui.form;\n");
      out.write("  //监听提交\n");
      out.write("\tform.on('submit(demo1)', function(data){\n");
      out.write("\t\n");
      out.write("\t\t//判断是否有 save() 方法，若有，则先执行 save()  这个方法是用户在输入模型中自己定义的\n");
      out.write("\t\tif(typeof(save) == 'function'){\n");
      out.write("\t\t\ttry{\n");
      out.write("\t\t\t\tvar s_return = save();\n");
      out.write("\t\t\t\tif(typeof(s_return) == 'boolean' && s_return == false){\n");
      out.write("\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}catch(err){}\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\t\tparent.iw.loading(\"保存中\");    //显示“操作中”的等待提示\n");
      out.write("\t\t//创建FormData对象，获取到form表单的相关数据\n");
      out.write("\t\tvar formobj =  document.getElementById(\"form\");\n");
      out.write("\t\tvar data = new FormData(formobj);\n");
      out.write("\t\n");
      out.write("\t    //为FormData对象添加上传图片的数据，这里由3.11版本更新后，图片单独上传，此项废弃\n");
      out.write("\t    //$.each($('#titlePicFile')[0].files, function(i, file) {\n");
      out.write("\t    //    data.append('titlePicFile', file);\n");
      out.write("\t    //});\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl:'");
      out.print(basePath );
      out.write("news/saveNews.do',\n");
      out.write("\t        type:'POST',\n");
      out.write("\t        data:data,\n");
      out.write("\t        cache: false,\n");
      out.write("\t        contentType: false,    //不可缺\n");
      out.write("\t        processData: false,    //不可缺\n");
      out.write("\t        success:function(data){\n");
      out.write("\t        \tparent.iw.loadClose();    //关闭“操作中”的等待提示\n");
      out.write("\t        \tif(data.result == '1'){\n");
      out.write("\t\t\t        //上传成功\n");
      out.write("\t            \tparent.iw.msgSuccess('保存成功');\n");
      out.write("\t            \twindow.location.href='listForTemplate.do?cid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${news.cid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("\t\t\t    }else if(data.result == '0'){\n");
      out.write("\t\t\t        parent.iw.msgFailure(data.info);\n");
      out.write("\t\t\t    }else{\n");
      out.write("\t\t\t        parent.iw.msgFailure();\n");
      out.write("\t\t\t    }\n");
      out.write("\t        },\n");
      out.write("\t        error:function(){\n");
      out.write("\t        \tparent.iw.loadClose();    //关闭“操作中”的等待提示\n");
      out.write("\t        \tparent.iw.msgFailure('出错');\n");
      out.write("\t        }\n");
      out.write("\t\t});\n");
      out.write("    return false;\n");
      out.write("  });\n");
      out.write("  \n");
      out.write("});\n");
      out.write("\n");
      out.write("//载入素材库\n");
      out.write("function loadSuCai(){\n");
      out.write("\t//加载素材的支持库\n");
      out.write("\tdynamicLoading.js(resBasePath+\"ueditor/template/load.js\");\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
