/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2019-02-19 00:43:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.column;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xnx3.DateUtil;
import com.xnx3.j2ee.Global;
import com.xnx3.wangmarket.admin.G;

public final class popupColumnForTemplate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1430113524000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.xnx3.j2ee.Global");
    _jspx_imports_classes.add("com.xnx3.wangmarket.admin.G");
    _jspx_imports_classes.add("com.xnx3.DateUtil");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write('\n');
      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../iw/common/head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("编辑栏目", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"");
      out.print(basePath+Global.CACHE_FILE );
      out.write("SiteColumn_used.js\"></script>\n");
      out.write("<script src=\"");
      out.print(basePath+Global.CACHE_FILE );
      out.write("SiteColumn_type.js\"></script>\n");
      out.write("<script src=\"");
      out.print(basePath+Global.CACHE_FILE );
      out.write("SiteColumn_editMode.js\"></script>\n");
      out.write("<script src=\"");
      out.print(basePath+Global.CACHE_FILE );
      out.write("SiteColumn_listRank.js\"></script>\n");
      out.write("<script src=\"");
      out.print(basePath+Global.CACHE_FILE );
      out.write("SiteColumn_useGenerateView.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<form id=\"form\" method=\"post\" class=\"layui-form\" style=\"padding:0px;margin-bottom: 10px; margin-top:0px;\">\n");
      out.write("\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"id\">\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("<div class=\"layui-tab layui-tab-card\" style=\"border-style: none; box-shadow: 0 0px 0px 0 rgba(0,0,0,.1); margin-top: 0px;\">\n");
      out.write("  <ul class=\"layui-tab-title\">\n");
      out.write("    <li class=\"layui-this\">基本设置</li>\n");
      out.write("    <li>信息录入</li>\n");
      out.write("    <li>高级设置</li>\n");
      out.write("  </ul>\n");
      out.write("  <div class=\"layui-tab-content\" style=\"padding-right: 35px;\">\n");
      out.write("    <div class=\"layui-tab-item layui-show\">\n");
      out.write("    \t<div class=\"layui-form-item\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"label_columnName\">栏目名称</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"name\" lay-verify=\"name\" autocomplete=\"off\" placeholder=\"限40个字符以内\" class=\"layui-input\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"layui-form-item\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"parentColumnCode_label\">所属栏目</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<select name=\"parentCodeName\" id=\"parentCodeName\">\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${parentColumnOption}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"layui-form-item\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"columnType\">栏目类型</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<select name=\"type\" required=\"type\" lay-verify=\"type\" lay-filter=\"type\" id=\"type\">\n");
      out.write("\t\t\t\t\t<option value=\"\">请选择</option>\n");
      out.write("\t\t\t\t\t<option value=\"7\" ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(">信息列表</option>\n");
      out.write("\t\t\t\t\t<option value=\"8\" ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write(">独立页面</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"layui-form-item\" id=\"xnx3_listTemplate\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"listTemplate\">列表模版</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<select name=\"templatePageListName\" lay-verify=\"listTemplateVerify\" id=\"templatePageListName\">\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tpl_list_option}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"layui-form-item\" id=\"xnx3_viewTemplate\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"viewTemplate\">内容模版</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<select name=\"templatePageViewName\" id=\"templatePageViewName\">\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tpl_view_option}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"layui-form-item\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"columnCode\">栏目代码</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"codeName\" lay-verify=\"required\" autocomplete=\"off\" placeholder=\"限20个字符以内\" class=\"layui-input\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.codeName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"layui-form-item\" id=\"listnum\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"listnum_label\">列表条数</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<input type=\"number\" name=\"listNum\" autocomplete=\"off\" placeholder=\"列表页面每页显示的条数\" class=\"layui-input\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.listNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("    </div>\n");
      out.write("    <div class=\"layui-tab-item\">\n");
      out.write("    \t<!-- 信息录入 -->\n");
      out.write("    \t\n");
      out.write("    \t<!-- 内容编辑方式，当独立页面时才会有效，才会显示。选择是使用内容富文本编辑框编辑，还是使用模板的方式编辑 -->\n");
      out.write("\t\t<div class=\"layui-form-item\" id=\"xnx3_editMode\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"columnEditMode\">编辑方式</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">writeSelectAllOptionForeditMode_('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.editMode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','', true);</script>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("    \t\n");
      out.write("    \t<div class=\"layui-form-item neirongguanli_shuru\" id=\"inputModel\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"inputModel_label\">输入模型</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<select name=\"inputModelCodeName\" id=\"inputModelCodeName\">\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inputModelOptions }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div style=\"padding-left: 30px; font-size: 12px; color: gray;padding-bottom: 10px;\" class=\"neirongguanli_shuru\">\n");
      out.write("\t\t\t<hr>\n");
      out.write("\t\t\t以下是当你进入 “内容管理” 中进行编辑文章时，是否显示这几个录入项\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("    \t\n");
      out.write("<style>\n");
      out.write(".layui-form-switch em {\n");
      out.write("\tfont-size: 15px;\n");
      out.write("}\n");
      out.write("</style>    \t\n");
      out.write("    \t<div class=\"layui-form-item neirongguanli_shuru\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"label_editUseTitlepic\">标题图片</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"editUseTitlepic\" lay-skin=\"switch\" lay-text=\"显示|隐藏\" value=\"1\" ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write(">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"layui-form-item neirongguanli_shuru\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"label_editUseExtendPhotos\">文章图集</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"editUseExtendPhotos\" lay-skin=\"switch\" lay-text=\"显示|隐藏\" value=\"1\" ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"layui-form-item neirongguanli_shuru\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"label_editUseIntro\">内容简介</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"editUseIntro\" lay-skin=\"switch\" lay-text=\"显示|隐藏\" value=\"1\" ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write(">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"layui-form-item neirongguanli_shuru\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"label_editUseText\">内容正文</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<input type=\"checkbox\" name=\"editUseText\" lay-skin=\"switch\" lay-text=\"显示|隐藏\" value=\"1\" ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write(">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("    </div>\n");
      out.write("    <div class=\"layui-tab-item\">\n");
      out.write("    \t<!-- 高级方式 -->\n");
      out.write("    \t\n");
      out.write("\t\t<div class=\"layui-form-item\" id=\"listRank\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"listRank_label\">信息排序</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">writeSelectAllOptionForlistRank_('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.listRank }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','请选择', false);</script>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"layui-form-item\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"xianshi_label\">是否显示</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">writeSelectAllOptionForused_('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.used }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','请选择', true);</script>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"layui-form-item\" id=\"useGenerateView_div\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"useGenerateView_label\">生成内容页</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">writeSelectAllOptionForuseGenerateView_('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.useGenerateView }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("','请选择', true);</script>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("    \t\n");
      out.write("\t\t<!-- 标题图片、封面图片。若是使用，可以在 栏目管理 中，编辑栏目时，有个 信息录入的选项卡，找到 标题图片，点击 使用 即可。若是自己添加的输入模型，请保留 id=\"sitecolumn_editUseTitlepic\" ,不然栏目设置中的是否使用图集功能将会失效！ -->\n");
      out.write("\t\t<div class=\"layui-form-item\" id=\"icon_div\">\n");
      out.write("\t\t\t<label class=\"layui-form-label\" id=\"label_columnName\">栏目图片</label>\n");
      out.write("\t\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t\t<input name=\"icon\" id=\"titlePicInput\" type=\"text\" autocomplete=\"off\" placeholder=\"点击右侧添加\" class=\"layui-input\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.icon }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"padding-right: 120px;\">\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"layui-btn\" id=\"uploadImagesButton\" style=\"float: right;margin-top: -38px;\">\n");
      out.write("\t\t\t\t\t<i class=\"layui-icon layui-icon-upload\"></i>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${icon }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"titlePicA\" style=\"float: right;margin-top: -38px;margin-right: 60px;\" title=\"预览原始图片\" target=\"_black\">\n");
      out.write("\t\t\t\t\t<img id=\"titlePicImg\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${icon }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("?x-oss-process=image/resize,h_38\" onerror=\"this.style.display='none';\" style=\"height: 36px;max-width: 57px; padding-top: 1px;\" alt=\"预览原始图片\">\n");
      out.write("\t\t\t\t</a><input class=\"layui-upload-file\" type=\"file\" name=\"fileName\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("    \t\n");
      out.write("    \t\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t<div class=\"layui-form-item\" style=\"padding-top:15px;\">\n");
      out.write("\t\t<div class=\"layui-input-block\">\n");
      out.write("\t\t\t<button class=\"layui-btn\" lay-submit=\"\" lay-filter=\"demo1\">保存修改</button>\n");
      out.write("\t\t\t<button type=\"reset\" class=\"layui-btn layui-btn-primary\">重置</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<div style=\"padding:10px;color:#e2e2e2; padding-bottom: 2px; width:100%; text-align:center; box-sizing: border-box;\">\n");
      out.write("\t\t提示：鼠标放到左侧描述,可显示当前说明\n");
      out.write("\t</div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("//自适应弹出层大小\n");
      out.write("var index = parent.layer.getFrameIndex(window.name); //获取窗口索引\n");
      out.write("parent.layer.iframeAuto(index);\n");
      out.write("\n");
      out.write("layui.use(['form', 'layedit', 'laydate', 'element'], function(){\n");
      out.write("  var form = layui.form;\n");
      out.write("\n");
      out.write("  //自定义验证规则\n");
      out.write("  form.verify({\n");
      out.write("    name: function(value){\n");
      out.write("      if(value.length == 0 || value.length > 40){\n");
      out.write("        return '请输入40个字以内的栏目名称';\n");
      out.write("      }\n");
      out.write("    },\n");
      out.write("    type: function(value){\n");
      out.write("      if(value=='' || value.length ==0){\n");
      out.write("        return '请选择栏目类型';\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("  });\n");
      out.write("  \n");
      out.write("\t//当类型发生变动改变\n");
      out.write("\tform.on('select(type)', function (data) {\n");
      out.write("\t\tselectTypeChange();\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t//当编辑方式发生变动改变\n");
      out.write("\tform.on('select(editMode)', function (data) {\n");
      out.write("\t\tselectEditMode();\n");
      out.write("\t});\n");
      out.write("  \n");
      out.write("  //监听提交\n");
      out.write("  form.on('submit(demo1)', function(data){\n");
      out.write("  \t\tparent.iw.loading('保存中');\n");
      out.write("\t\tvar d=$(\"form\").serialize();\n");
      out.write("        $.post(\"");
      out.print(basePath );
      out.write("column/savePopupColumnGaoJiUpdate.do\", d, function (result) { \n");
      out.write("        \tparent.iw.loadClose();\n");
      out.write("        \tvar obj = JSON.parse(result);\n");
      out.write("        \tif(obj.result == '1'){\n");
      out.write("        \t\tparent.parent.iw.msgSuccess(\"操作成功\");\n");
      out.write("        \t\tparent.location.reload();\t//刷新父窗口\n");
      out.write("        \t\tparent.layer.close(index);\n");
      out.write("        \t}else if(obj.result == '0'){\n");
      out.write("        \t\tparent.layer.msg(obj.info, {shade: 0.3})\n");
      out.write("        \t}else{\n");
      out.write("        \t\tparent.layer.msg(result, {shade: 0.3})\n");
      out.write("        \t}\n");
      out.write("         }, \"text\");\n");
      out.write("\t\t\n");
      out.write("    return false;\n");
      out.write("  });\n");
      out.write("  \n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("layui.use('upload', function(){\n");
      out.write("\tvar upload = layui.upload;\n");
      out.write("\t//上传图片,封面图\n");
      out.write("\t//upload.render(uploadPic);\n");
      out.write("\tupload.render({\n");
      out.write("\t\telem: \"#uploadImagesButton\" //绑定元素\n");
      out.write("\t\t,url: '");
      out.print(basePath );
      out.write("site/uploadImage.do' //上传接口\n");
      out.write("\t\t,field: 'image'\n");
      out.write("\t\t,accept: 'file'\n");
      out.write("\t\t,size: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maxFileSizeKB}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\t\t,exts:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ossFileUploadImageSuffixList }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\t//可上传的文件后缀\n");
      out.write("\t\t,done: function(res){\n");
      out.write("\t\t\t//上传完毕回调\n");
      out.write("\t\t\tloadClose();\n");
      out.write("\t\t\tif(res.result == 1){\n");
      out.write("\t\t\t\ttry{\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"titlePicInput\").value = res.url;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"titlePicA\").href = res.url;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"titlePicImg\").src = res.url;\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"titlePicImg\").style.display='';\t//避免新增加的文章，其titlepicImg是隐藏的\n");
      out.write("\t\t\t\t}catch(err){}\n");
      out.write("\t\t\t\tparent.iw.msgSuccess(\"上传成功\");\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\tparent.iw.msgFailure(res.info);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t,error: function(index, upload){\n");
      out.write("\t\t\t//请求异常回调\n");
      out.write("\t\t\tparent.iw.loadClose();\n");
      out.write("\t\t\tparent.iw.msgFailure();\n");
      out.write("\t\t}\n");
      out.write("\t\t,before: function(obj){ //obj参数包含的信息，跟 choose回调完全一致，可参见上文。\n");
      out.write("\t\t\tparent.iw.loading('上传中..');\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t//上传图片,图集，v4.6扩展\n");
      out.write("\tupload.render(uploadExtendPhotos);\n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("//鼠标跟随提示\n");
      out.write("$(function(){\n");
      out.write("\t//栏目名称\n");
      out.write("\tvar label_columnName_index = 0;\n");
      out.write("\t$(\"#label_columnName\").hover(function(){\n");
      out.write("\t\tlabel_columnName_index = layer.tips('给当前栏目起个名字吧。这里的名字可以直接在网站里调出显示，也可以在内容管理中显示栏目的名字。', '#label_columnName', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(label_columnName_index);\n");
      out.write("\t})\n");
      out.write("\n");
      out.write("\t//列表页模版\n");
      out.write("\tvar listTemplate_index = 0;\n");
      out.write("\t$(\"#listTemplate\").hover(function(){\n");
      out.write("\t\tlistTemplate_index = layer.tips('当前栏目信息展示给用户看时，的列表页面模版<br/>比如，新闻列表、产品列表、成功案例列表等此类信息列表。<br/>若这里为空，那肯定就是还没有创建过列表页模版了，先去<b>模版页面</b>去创建一个列表页模版吧', '#listTemplate', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(listTemplate_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t//编辑方式\n");
      out.write("\tvar columnEditMode_index = 0;\n");
      out.write("\t$(\"#columnEditMode\").hover(function(){\n");
      out.write("\t\tcolumnEditMode_index = layer.tips('编辑方式，设定其填充/编辑内容信息的编辑方式。<br/>1.&nbsp;<b>在内容管理中编辑</b>，系统默认的内容编辑，比如添加新闻、图文时，都可以使用这个。若对此详不是太了解，一律选择此项即可。<br/>2.&nbsp;<b>在模版页面中编辑</b>，直接编辑模版页面的方式进行编辑，同样，编辑的工具是模版页，也就是直接对模版页面进行编辑。<br/><b style=\"font-size:16px; padding:6px;\">注意，若是不理解，请勿改动本项。</b>', '#columnEditMode', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(columnEditMode_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t//内容页模版\n");
      out.write("\tvar viewTemplate_index = 0;\n");
      out.write("\t$(\"#viewTemplate\").hover(function(){\n");
      out.write("\t\tviewTemplate_index = layer.tips('当前栏目信息展示给用户看时，的内容页面模版<br/>比如，新闻详情、产品详情、公司介绍、联系我们等页面，都是单独的一个内容介绍页面<br/>若这里为空，那肯定就是还没有创建过内容页模版了，先去<b>模版页面</b>去创建一个内容页模版吧', '#viewTemplate', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(viewTemplate_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t//栏目类型\n");
      out.write("\tvar columnType_index = 0;\n");
      out.write("\t$(\"#columnType\").hover(function(){\n");
      out.write("\t\t//这里通常使用的有这么三种：<br/><b>新闻信息</b>：像是新闻列表、动态资讯，这种纯文字性质的列表，并点击某项后可进入查看详情<br/><b>图文信息</b>：像是产品展示、案例展示等，图片＋文字形式的列表，并点击项后进入查看详情<br/><b>独立页面</b>：像是公司简介、联系我们、招商加盟这种单独的页面\n");
      out.write("\t\tcolumnType_index = layer.tips('<b>信息列表</b>：像是新闻列表、动态资讯、产品展示等，这种信息的列表。这个栏目内的文章条数不固定，用户可以随意添加多条信息。<br/><b>独立页面</b>：像是公司简介、联系我们这种的，一个栏目就只有一个页面的', '#columnType', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(columnType_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t//栏目代码\n");
      out.write("\tvar columnCode_index = 0;\n");
      out.write("\t$(\"#columnCode\").hover(function(){\n");
      out.write("\t\tcolumnCode_index = layer.tips('1.&nbsp;网站中，每个栏目都有一个唯一的栏目代码，在模版中动态调用某个栏目、或某个栏目下的动态数据时，就是根据这个栏目的栏目代码来进行调取的。<br/>2.&nbsp;此处强烈建议使用英文或拼音，禁止特殊字符<br/>3.&nbsp;<b>提示：生成的页面就是以这里命名的。填的栏目代码.html</b>。例如，你的栏目代码设置为aboutus，那么你这个页面的地址便是你的域名/aboutus.html<br/>4.&nbsp;栏目代码设置好后最好不要再改动！模版页面、模版栏目中动态调用栏目就是使用的这个；还有栏目的备份还原也是使用的栏目代码！', '#columnCode', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(columnCode_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t//上级栏目\n");
      out.write("\tvar parentColumnCode_index = 0;\n");
      out.write("\t$(\"#parentColumnCode_label\").hover(function(){\n");
      out.write("\t\tparentColumnCode_index = layer.tips('您当前操作的栏目，是属于哪个栏目下的。<br/>若选顶级栏目，则此栏目不属于任何栏目，是顶级栏目<br/><b>注意，模版中动态调取数据只支持一级子栏目</b>', '#parentColumnCode_label', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(parentColumnCode_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t//输入模型\n");
      out.write("\tvar inputModel_index = 0;\n");
      out.write("\t$(\"#inputModel_label\").hover(function(){\n");
      out.write("\t\tinputModel_index = layer.tips('本栏目建立好后，在<b>内容管理</b>中操作本栏目的具体数据时，数据录入的样式。<br/>可在<b>模板管理</b>-<b>输入模型</b>中进行修改<b><br/><b style=\"font-size:16px; padding:6px;\">注意，若是不理解，请勿改动本项。</b>', '#inputModel_label', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(inputModel_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t//列表条数，列表页面的显示条数\n");
      out.write("\tvar listnum_index = 0;\n");
      out.write("\t$(\"#listnum_label\").hover(function(){\n");
      out.write("\t\tlistnum_index = layer.tips('当前列表页面，每个列表页显示多少条数据。<br/>如新闻列表，再生成后，用户查看新闻列表时，每页显示多少条新闻', '#listnum_label', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(listnum_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t//显示\n");
      out.write("\tvar xianshi_index = 0;\n");
      out.write("\t$(\"#xianshi_label\").hover(function(){\n");
      out.write("\t\txianshi_index = layer.tips('绝大多数时候，都是显示即可，显示即正常使用。<br/>若是隐藏，在 内容管理 中不会显示此栏目、另外在模版页面中使用动态栏目代码调取子栏目列表时，也不会调取到', '#xianshi_label', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(xianshi_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t//listRank ，信息排序\n");
      out.write("\tvar listRank_index = 0;\n");
      out.write("\t$(\"#listRank_label\").hover(function(){\n");
      out.write("\t\tlistRank_index = layer.tips('当前栏目内，内容信息排序方式。有以下两种：<br>1.&nbsp;<b>发布时间倒序</b>：发布时间越晚，排序越靠前。<br/>2.&nbsp;<b>发布时间正序</b>：发布时间越早，排序越靠前', '#listRank_label', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(listRank_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t//内容管理中，是否使用标题图片\n");
      out.write("\tvar label_editUseTitlepic_index = 0;\n");
      out.write("\t$(\"#label_editUseTitlepic\").hover(function(){\n");
      out.write("\t\tlabel_editUseTitlepic_index = layer.tips('标题图片，也就是文章的封面图，让每篇文章都有自己的一个封面图。比如，这个封面图可以是网站中，产品列表页面的每个产品的图片。', '#label_editUseTitlepic', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(label_editUseTitlepic_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t//内容管理中，是否使用图集\n");
      out.write("\tvar label_editUseExtendPhotos_index = 0;\n");
      out.write("\t$(\"#label_editUseExtendPhotos\").hover(function(){\n");
      out.write("\t\tlabel_editUseExtendPhotos_index = layer.tips('文章图集，也就是让每篇文章都有自己的图集，一篇文章里面，可以上传不固定数量的多张图片，可以在网站中，做出轮播图等效果', '#label_editUseExtendPhotos', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(label_editUseExtendPhotos_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t//内容管理中，是否使用内容简介\n");
      out.write("\tvar label_editUseIntro_index = 0;\n");
      out.write("\t$(\"#label_editUseIntro\").hover(function(){\n");
      out.write("\t\tlabel_editUseIntro_index = layer.tips('内容简介，也就是让本栏目中的每篇文章都可以编辑自己的内容简介。这些简介文字，可以在网站中，进行调取出来，比如在新闻列表中，作为新闻的简介说明。<br/>如果设置为不显示，内容简介也会有信息，会自动从内容正文中截取前120个字符作为内容简介的信息。', '#label_editUseIntro', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(label_editUseIntro_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t//内容管理中，是否使用内容正文\n");
      out.write("\tvar label_editUseText_index = 0;\n");
      out.write("\t$(\"#label_editUseText\").hover(function(){\n");
      out.write("\t\tlabel_editUseText_index = layer.tips('内容正文，也就是文章的正文、详情。也就是富文本编辑器UEditor编辑的区域，可以通过这里进行随意布局、上传图片、附件、表情、以及插入地图等！', '#label_editUseText', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(label_editUseText_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\t//是否生成内容详情页面\n");
      out.write("\tvar useGenerateView_label_index = 0;\n");
      out.write("\t$(\"#useGenerateView_label\").hover(function(){\n");
      out.write("\t\tuseGenerateView_label_index = layer.tips('是否生成内容详情页面？<br/>如果您这个栏目只是要做一个列表，不做点击进入的详情页面的话，即无内容详情页，也就是此处可以设置为不生成内容页面，可以提高生成整站的速度。<br/><b>注意，若是不懂，请勿改动此处！</b>', '#useGenerateView_label', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['310px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(useGenerateView_label_index);\n");
      out.write("\t})\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("});\t\n");
      out.write("\n");
      out.write("//当类型改变后，相应的自定义网址也会显示或者隐藏、模版也会相应显示或者隐藏\n");
      out.write("function selectTypeChange(){\n");
      out.write("\tdocument.getElementById(\"xnx3_viewTemplate\").style.display=\"none\";\t//内容模版\n");
      out.write("\tdocument.getElementById(\"xnx3_listTemplate\").style.display=\"none\";\t//列表模版\n");
      out.write("\tdocument.getElementById(\"listnum\").style.display=\"none\";\t\t\t\t//列表页面每页显示多少条\n");
      out.write("\t\n");
      out.write("\tif(document.getElementById(\"type\").options[1].selected){\n");
      out.write("\t\t//列表页面（新闻、图文等）\n");
      out.write("\t\tdocument.getElementById(\"xnx3_viewTemplate\").style.display=\"\";\n");
      out.write("\t\tdocument.getElementById(\"xnx3_listTemplate\").style.display=\"\";\n");
      out.write("\t\tdocument.getElementById(\"listnum\").style.display=\"\";\n");
      out.write("\t\tdocument.getElementById(\"xnx3_editMode\").style.display=\"none\";\n");
      out.write("\t\tdocument.getElementById(\"listRank\").style.display=\"\";\n");
      out.write("\t\tdocument.getElementById(\"useGenerateView_div\").style.display=\"\";\n");
      out.write("\t}else if(document.getElementById(\"type\").options[2].selected){\n");
      out.write("\t\t//独立页面\n");
      out.write("\t\tdocument.getElementById(\"xnx3_viewTemplate\").style.display=\"\";\n");
      out.write("\t\tdocument.getElementById(\"xnx3_editMode\").style.display=\"\";\n");
      out.write("\t\tdocument.getElementById(\"listRank\").style.display=\"none\";\n");
      out.write("\t\tdocument.getElementById(\"useGenerateView_div\").style.display=\"none\";\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("selectTypeChange();\n");
      out.write("\n");
      out.write("//当编辑方式放生改变\n");
      out.write("function selectEditMode(){\n");
      out.write("\tif(document.getElementById(\"editMode\").options[2].selected){\n");
      out.write("\t\t//模板式编辑，将不显示输入模型、以及图集、内容等输入选项\n");
      out.write("\t\t$(\".neirongguanli_shuru\").hide();\n");
      out.write("\t}else{\n");
      out.write("\t\t$(\".neirongguanli_shuru\").show();\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("selectEditMode();\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../iw/common/foot.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/view/column/popupColumnForTemplate.jsp(52,23) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.type=='7'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" selected=\"selected\"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f0_reused) {
        _jspx_th_c_005fif_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/view/column/popupColumnForTemplate.jsp(53,23) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.type=='8'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" selected=\"selected\"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f1_reused) {
        _jspx_th_c_005fif_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f1);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/view/column/popupColumnForTemplate.jsp(125,95) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.editUseTitlepic=='1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" checked");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f2_reused) {
        _jspx_th_c_005fif_005f2.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f2);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/view/column/popupColumnForTemplate.jsp(131,99) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.editUseExtendPhotos=='1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" checked");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f3_reused) {
        _jspx_th_c_005fif_005f3.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f3);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/view/column/popupColumnForTemplate.jsp(137,92) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.editUseIntro=='1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" checked");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f4_reused) {
        _jspx_th_c_005fif_005f4.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f4);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/view/column/popupColumnForTemplate.jsp(143,91) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${siteColumn.editUseText=='1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" checked");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f5_reused) {
        _jspx_th_c_005fif_005f5.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f5);
      }
    }
    return false;
  }
}
