/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2019-01-24 01:05:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.site;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xnx3.j2ee.Global;

public final class baseInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1430113524000L));
    _jspx_dependants.put("/WEB-INF/lib/xnx3_tld.jar", Long.valueOf(1512734430000L));
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/xnx3_tld.jar!/META-INF/xnx3.tld", Long.valueOf(1495004768000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.xnx3.j2ee.Global");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005ftime_0026_005flinuxTime_005fformat_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fx_005ftime_0026_005flinuxTime_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fx_005ftime_0026_005flinuxTime_005fformat_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fx_005ftime_0026_005flinuxTime_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fx_005ftime_0026_005flinuxTime_005fformat_005fnobody.release();
    _005fjspx_005ftagPool_005fx_005ftime_0026_005flinuxTime_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../iw/common/head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("基本信息", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("\n");
      out.write("<body style=\"text-align:left; min-width:10px;\">\n");
      out.write("<script src=\"");
      out.print(basePath+Global.CACHE_FILE );
      out.write("Site_mShowBanner.js\"></script>\n");
      out.write("\n");
      out.write("<div class=\"weui_cells weui_cells_access\" style=\"margin-top: 0em;\">\n");
      out.write("\t\n");
      out.write(" <a class=\"weui_cell\" href=\"../productPrice.do\" style=\"display:none;\">\n");
      out.write("   <div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("     <p>产品介绍</p>\n");
      out.write("   </div>\n");
      out.write("   <div class=\"weui_cell_ft\">按量计费</div>\n");
      out.write(" </a>\n");
      out.write(" <a class=\"weui_cell\" href=\"../user/invite.do\" style=\"display:none;\">\n");
      out.write("   <div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("     <p>我的下线</p>\n");
      out.write("   </div>\n");
      out.write("   <div class=\"weui_cell_ft\">下线列表</div>\n");
      out.write(" </a>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"weui_cells\" style=\"margin-top:0px;\">\n");
      out.write("  \n");
      out.write("  <div class=\"weui_cell\" style=\"display:none;\">\n");
      out.write("    <div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("      <p>我的");
      out.print(Global.get("CURRENCY_NAME") );
      out.write("</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"weui_cell_ft\" style=\"color: #9717F7;cursor: pointer;\" onclick=\"window.parent.openMoneyIndex();\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.currency }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.print(Global.get("CURRENCY_NAME") );
      out.write("</div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"weui_cell\">\n");
      out.write("    <div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("      <p>到期时间</p>\n");
      out.write("    </div>\n");
      out.write("    <a href=\"javascript:parent.jumpParentAgency();;\" id=\"yanchangriqi\" class=\"layui-btn layui-btn-primary\" style=\"height: 30px;line-height: 30px;padding: 0 10px;font-size: 12px;margin-right: 10px;\">延长</a>\n");
      out.write("    <div class=\"weui_cell_ft\">\n");
      out.write("    \t");
      if (_jspx_meth_x_005ftime_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"weui_cell\">\n");
      out.write("    <div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("      <p>空间占用</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"weui_cell_ft\" id=\"ossSize\">计算中...</div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"weui_cell\">\n");
      out.write("    <div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("      <p>空间总量</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"weui_cell_ft\">\n");
      out.write("    \t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.ossSizeHave}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&nbsp;MB\n");
      out.write("    \t<!-- <a href=\"../productPrice.do\" class=\"weui_btn weui_btn_mini weui_btn_primary\" style=\"margin-left:10px;\">升级</a> -->\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"weui_cell\">\n");
      out.write("    <div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("      <p>剩余空间</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"weui_cell_ft\" id=\"residueSize\">计算中...</div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"weui_cell\">\n");
      out.write("    <div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("      <p>注册时间</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"weui_cell_ft\">");
      if (_jspx_meth_x_005ftime_005f1(_jspx_page_context))
        return;
      out.write("</div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"weui_cell\">\n");
      out.write("    <div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("      <p>最后登陆</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"weui_cell_ft\">");
      if (_jspx_meth_x_005ftime_005f2(_jspx_page_context))
        return;
      out.write("</div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("//自适应弹出层大小\n");
      out.write("var index = parent.layer.getFrameIndex(window.name); //获取窗口索引\n");
      out.write("parent.layer.iframeAuto(index);\n");
      out.write("\n");
      out.write("\n");
      out.write("$(function(){\n");
      out.write("\t//延长期限按钮\n");
      out.write("\tvar yanchangriqi_tipindex = 0;\n");
      out.write("\t$(\"#yanchangriqi\").hover(function(){\n");
      out.write("\t\tyanchangriqi_tipindex = layer.tips('点击按钮联系我们，为您延长使用期限', '#yanchangriqi', {\n");
      out.write("\t\t\ttips: [2, '#0FA6A8'], //还可配置颜色\n");
      out.write("\t\t\ttime:0,\n");
      out.write("\t\t\ttipsMore: true,\n");
      out.write("\t\t\tarea : ['200px' , 'auto']\n");
      out.write("\t\t});\n");
      out.write("\t},function(){\n");
      out.write("\t\tlayer.close(yanchangriqi_tipindex);\n");
      out.write("\t})\n");
      out.write("});\n");
      out.write("\n");
      out.write("$.post(\"");
      out.print(basePath );
      out.write("site/getOSSSize.do\", function(data){\n");
      out.write("\tif(data.result == '1'){\n");
      out.write("\t\tdocument.getElementById('ossSize').innerHTML = (data.info/1000)+'&nbsp;MB';\n");
      out.write("\t\tdocument.getElementById('residueSize').innerHTML = (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.ossSizeHave}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("-(data.info/1000))+'&nbsp;MB';\n");
      out.write("\t}else{\n");
      out.write("\t\tparent.iw.msgFailure(data.info);\n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_x_005ftime_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:time
    com.xnx3.tld.TimeTag _jspx_th_x_005ftime_005f0 = (com.xnx3.tld.TimeTag) _005fjspx_005ftagPool_005fx_005ftime_0026_005flinuxTime_005fformat_005fnobody.get(com.xnx3.tld.TimeTag.class);
    boolean _jspx_th_x_005ftime_005f0_reused = false;
    try {
      _jspx_th_x_005ftime_005f0.setPageContext(_jspx_page_context);
      _jspx_th_x_005ftime_005f0.setParent(null);
      // /WEB-INF/view/site/baseInfo.jsp(47,5) name = linuxTime type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005ftime_005f0.setLinuxTime(((java.lang.Long) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.expiretime }", long.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).longValue());
      // /WEB-INF/view/site/baseInfo.jsp(47,5) name = format type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005ftime_005f0.setFormat("yyyy-MM-dd");
      int _jspx_eval_x_005ftime_005f0 = _jspx_th_x_005ftime_005f0.doStartTag();
      if (_jspx_th_x_005ftime_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005ftime_0026_005flinuxTime_005fformat_005fnobody.reuse(_jspx_th_x_005ftime_005f0);
      _jspx_th_x_005ftime_005f0_reused = true;
    } finally {
      if (!_jspx_th_x_005ftime_005f0_reused) {
        _jspx_th_x_005ftime_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_x_005ftime_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_x_005ftime_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:time
    com.xnx3.tld.TimeTag _jspx_th_x_005ftime_005f1 = (com.xnx3.tld.TimeTag) _005fjspx_005ftagPool_005fx_005ftime_0026_005flinuxTime_005fnobody.get(com.xnx3.tld.TimeTag.class);
    boolean _jspx_th_x_005ftime_005f1_reused = false;
    try {
      _jspx_th_x_005ftime_005f1.setPageContext(_jspx_page_context);
      _jspx_th_x_005ftime_005f1.setParent(null);
      // /WEB-INF/view/site/baseInfo.jsp(75,30) name = linuxTime type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005ftime_005f1.setLinuxTime(((java.lang.Long) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.regtime }", long.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).longValue());
      int _jspx_eval_x_005ftime_005f1 = _jspx_th_x_005ftime_005f1.doStartTag();
      if (_jspx_th_x_005ftime_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005ftime_0026_005flinuxTime_005fnobody.reuse(_jspx_th_x_005ftime_005f1);
      _jspx_th_x_005ftime_005f1_reused = true;
    } finally {
      if (!_jspx_th_x_005ftime_005f1_reused) {
        _jspx_th_x_005ftime_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_x_005ftime_005f1);
      }
    }
    return false;
  }

  private boolean _jspx_meth_x_005ftime_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  x:time
    com.xnx3.tld.TimeTag _jspx_th_x_005ftime_005f2 = (com.xnx3.tld.TimeTag) _005fjspx_005ftagPool_005fx_005ftime_0026_005flinuxTime_005fnobody.get(com.xnx3.tld.TimeTag.class);
    boolean _jspx_th_x_005ftime_005f2_reused = false;
    try {
      _jspx_th_x_005ftime_005f2.setPageContext(_jspx_page_context);
      _jspx_th_x_005ftime_005f2.setParent(null);
      // /WEB-INF/view/site/baseInfo.jsp(81,30) name = linuxTime type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_x_005ftime_005f2.setLinuxTime(((java.lang.Long) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.lasttime }", long.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).longValue());
      int _jspx_eval_x_005ftime_005f2 = _jspx_th_x_005ftime_005f2.doStartTag();
      if (_jspx_th_x_005ftime_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fx_005ftime_0026_005flinuxTime_005fnobody.reuse(_jspx_th_x_005ftime_005f2);
      _jspx_th_x_005ftime_005f2_reused = true;
    } finally {
      if (!_jspx_th_x_005ftime_005f2_reused) {
        _jspx_th_x_005ftime_005f2.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_x_005ftime_005f2);
      }
    }
    return false;
  }
}
