/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2019-02-21 00:41:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.iw_005fupdate.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xnx3.j2ee.Global;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/E:/github/Project/智慧校园/微官网/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1550709623293L));
    _jspx_dependants.put("/WEB-INF/lib/xnx3_tld.jar", Long.valueOf(1550709623439L));
    _jspx_dependants.put("jar:file:/E:/github/Project/智慧校园/微官网/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/xnx3_tld.jar!/META-INF/xnx3.tld", Long.valueOf(1495004768000L));
    _jspx_dependants.put("jar:file:/E:/github/Project/智慧校园/微官网/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.xnx3.j2ee.Global");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../iw/common/head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("登录", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".myForm{\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("    width: 495px;\r\n");
      out.write("    height: 360px;\r\n");
      out.write("    border-width: 1px 1px 1px 1px;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    -webkit-box-shadow: 0 0 10px #e2e2e2;\r\n");
      out.write("    -moz-box-shadow: 0 0 10px #e2e2e2;\r\n");
      out.write("    box-shadow: 0 0 10px #e2e2e2;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    margin-left: -248px;\r\n");
      out.write("    margin-top: -181px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width:600px){\r\n");
      out.write("\t.myForm{\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    height: 100%;\r\n");
      out.write("\t    border-width: 0px;\r\n");
      out.write("\t    padding: 0px;\r\n");
      out.write("\t    border-radius: 0px;\r\n");
      out.write("\t    overflow: auto;\r\n");
      out.write("\t    -webkit-box-shadow: 0 0 0px #e2e2e2;\r\n");
      out.write("\t    -moz-box-shadow: 0 0 0px #e2e2e2;\r\n");
      out.write("\t    box-shadow: 0 0 0px #e2e2e2;\r\n");
      out.write("\t    position: static;\r\n");
      out.write("\t    left: 0px;\r\n");
      out.write("\t    top: 0px;\r\n");
      out.write("\t    margin-left: 0px;\r\n");
      out.write("\t    margin-top: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".touming{\r\n");
      out.write("\tbackground: rgba(0,190,150,0.1) none repeat scroll !important;\r\n");
      out.write("}\r\n");
      out.write(".baisetouming{\r\n");
      out.write("\tbackground: rgba(250,250,250,0.1) none repeat scroll !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- 背景 -->\r\n");
      out.write("<div class=\"layui-canvs\" style=\"position: fixed;top: 0px;left: 0px;z-index: -1;\"></div>\r\n");
      out.write("\r\n");
      out.write("<form class=\"layui-form layui-elem-quote layui-quote-nm myForm\">\r\n");
      out.write("  <div class=\"layui-form-item touming\" style=\"height: 70px;background-color: #eeeeee;line-height: 70px;text-align: center;font-size: 25px;color: #3F4056;\">\r\n");
      out.write("    ");
      out.print(Global.get("SITE_NAME") );
      out.write(" 云建站平台登陆\r\n");
      out.write("  </div>\r\n");
      out.write("  <div style=\"padding: 30px 50px 40px 0px;\">\r\n");
      out.write("  \t<div class=\"layui-form-item\">\r\n");
      out.write("\t    <label class=\"layui-form-label\">用户名</label>\r\n");
      out.write("\t    <div class=\"layui-input-block\">\r\n");
      out.write("\t      <input type=\"text\" name=\"username\" required  lay-verify=\"required\" placeholder=\"请输入 用户名/邮箱\" autocomplete=\"off\" class=\"layui-input baisetouming\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"layui-form-item\">\r\n");
      out.write("\t    <label class=\"layui-form-label\"> 密 码&nbsp;&nbsp; </label>\r\n");
      out.write("\t    <div class=\"layui-input-block\">\r\n");
      out.write("\t      <input type=\"password\" name=\"password\" required lay-verify=\"required\" placeholder=\"请输入密码\" autocomplete=\"off\" class=\"layui-input baisetouming\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"layui-form-item\">\r\n");
      out.write("\t    <label class=\"layui-form-label\"> 验证码 </label>\r\n");
      out.write("\t    <div class=\"layui-input-inline\">\r\n");
      out.write("\t      <input type=\"text\" name=\"code\" required lay-verify=\"required\" placeholder=\"请输入右侧验证码\" autocomplete=\"off\" class=\"layui-input baisetouming\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"layui-form-mid layui-word-aux\" style=\"padding-top: 3px;padding-bottom: 0px;\"><img id=\"code\" src=\"captcha.do\" onclick=\"reloadCode();\" style=\"height: 29px;width: 110px; cursor: pointer;\" /></div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"layui-form-item\" style=\"display:none\">\r\n");
      out.write("\t    <label class=\"layui-form-label\">记住密码</label>\r\n");
      out.write("\t    <div class=\"layui-input-block\">\r\n");
      out.write("\t      <input type=\"checkbox\" name=\"switch\" lay-skin=\"switch\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"layui-form-item\">\r\n");
      out.write("\t    <div class=\"layui-input-block\">\r\n");
      out.write("\t      <button class=\"layui-btn\" lay-submit lay-filter=\"formDemo\" style=\"opacity:0.6; margin-right: 50px;\">立即登陆</button>\r\n");
      out.write("\t      <button type=\"reset\" class=\"layui-btn layui-btn-primary baisetouming\" style=\"width: 90px;\">重置</button>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</form>\r\n");
      out.write(" \r\n");
      out.write("<!--[if IE]>\r\n");
      out.write("\t<div style=\"position: absolute;bottom: 0px;padding: 10px;text-align: center;width: 100%;background-color: yellow;\">建议使用<a href=\"https://www.baidu.com/s?wd=Chrome\" target=\"_black\" style=\"text-decoration:underline\">Chrome(谷歌)</a>、<a href=\"https://www.baidu.com/s?wd=Firefox\" target=\"_black\" style=\"text-decoration:underline\">Firefox(火狐)</a>浏览器，IE浏览器会无法操作！！！</div>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- weui -->\r\n");
      out.write("<script src=\"http://res.weiunity.com/js/jquery-2.1.4.js\"></script>\r\n");
      out.write("<script src=\"http://res.weiunity.com/js/jquery-weui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://res.weiunity.com/css/weui.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://res.weiunity.com/css/jquery-weui.css\">\r\n");
      out.write("<script>\r\n");
      out.write("//Demo\r\n");
      out.write("layui.use('form', function(){\r\n");
      out.write("  var form = layui.form;\r\n");
      out.write("  \r\n");
      out.write("  //监听提交\r\n");
      out.write("  form.on('submit(formDemo)', function(data){\r\n");
      out.write("  \t$.showLoading('登录中...');\r\n");
      out.write("    var d=$(\"form\").serialize();\r\n");
      out.write("\t$.post(\"");
      out.print(basePath );
      out.write("loginSubmit.do\", d, function (result) {\r\n");
      out.write("\t\t$.hideLoading();\r\n");
      out.write("       \tvar obj = JSON.parse(result);\r\n");
      out.write("       \tif(obj.result == '1'){\r\n");
      out.write("       \t\tlayer.msg('登陆成功', {shade: 0.3});\r\n");
      out.write("       \t\twindow.location.href=obj.info;\r\n");
      out.write("       \t}else if(obj.result == '0'){\r\n");
      out.write("       \t\t//登陆失败\r\n");
      out.write("       \t\treloadCode();\r\n");
      out.write("       \t\tlayer.msg(obj.info, {shade: 0.3})\r\n");
      out.write("       \t}else if(obj.result == '11'){\r\n");
      out.write("       \t\t//网站已过期。弹出提示\r\n");
      out.write("       \t\treloadCode();\r\n");
      out.write("       \t\tlayer.open({\r\n");
      out.write("\t\t\t  title: '到期提示'\r\n");
      out.write("\t\t\t  ,content: obj.info\r\n");
      out.write("\t\t\t});     \r\n");
      out.write("       \t}else{\r\n");
      out.write("       \t\treloadCode();\r\n");
      out.write("       \t\tlayer.msg(result, {shade: 0.3})\r\n");
      out.write("       \t}\r\n");
      out.write("\t}, \"text\");\r\n");
      out.write("    return false;\r\n");
      out.write("  });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//重新加载验证码\r\n");
      out.write("function reloadCode(){\r\n");
      out.write("var code=document.getElementById('code');\r\n");
      out.write("code.setAttribute('src','captcha.do?'+Math.random());\r\n");
      out.write("//这里必须加入随机数不然地址相同我发重新加载\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//检测浏览器，若不是Chrome浏览器，弹出提示\r\n");
      out.write("if(navigator.userAgent.indexOf('Chrome') == -1){\r\n");
      out.write("\tlayer.open({\r\n");
      out.write("\t  type: 1\r\n");
      out.write("\t  ,title:'提示'\r\n");
      out.write("\t  ,offset: 'rb' //具体配置参考：offset参数项\r\n");
      out.write("\t  ,content: '<div style=\"padding: 18px; line-height:30px;\">建议使用<a href=\"https://www.baidu.com/s?wd=Chrome\" target=\"_black\" style=\"text-decoration:underline\">Chrome(谷歌)</a>浏览器<br/>其他浏览器登录可能无法正常操作！</div>'\r\n");
      out.write("\t  ,btn: ['下载Chrome','忽略']\r\n");
      out.write("\t  ,btnAlign: 'c' //按钮居中\r\n");
      out.write("\t  ,shade: 0 //不显示遮罩\r\n");
      out.write("\t  ,yes: function(){\r\n");
      out.write("\t    layer.closeAll();\r\n");
      out.write("\t    window.open(\"https://www.baidu.com/s?wd=Chrome\");\r\n");
      out.write("\t  }\r\n");
      out.write("\t  ,btn2: function(){\r\n");
      out.write("\t    layer.closeAll();\r\n");
      out.write("\t  }\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 以下为背景特效相关 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("'use strict';\r\n");
      out.write("layui.use(['jquery'],function(){\r\n");
      out.write("\twindow.jQuery = window.$ = layui.jquery;\r\n");
      out.write("   $(\".layui-canvs\").width($(window).width());\r\n");
      out.write("   $(\".layui-canvs\").height($(window).height());\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://res.weiunity.com/js/jparticle.jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\".layui-canvs\").jParticle({\r\n");
      out.write("\t\tbackground: \"#FFFFFF\",\r\n");
      out.write("\t\tcolor: \"#FDFDFD\"\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 背景特效相关结束 -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
