/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2019-01-23 09:06:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.iw_005fupdate.install;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xnx3.j2ee.Global;

public final class installSuccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1430113524000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.xnx3.j2ee.Global");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("  \n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../iw/common/head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("设置阿里云AccessKey参数", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div style=\"padding:30px; padding-bottom:10px; text-align:center; font-size:20px;\">\n");
      out.write("\t恭喜您，系统安装配置成功！网市场云建站系统，共分为三种管理后台，如下所示，请查看！\n");
      out.write("\t<a href=\"delete.do\" target=\"_black\" style=\"font-size:12px;\">删除安装文件</a>\n");
      out.write("\t<br/>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<style>\n");
      out.write("\t.sanhoutai{\n");
      out.write("\t\ttext-align:left;\n");
      out.write("\t}\n");
      out.write("\t.sanhoutai>div{\n");
      out.write("\t\tfloat:left;\n");
      out.write("\t\twidth:30%;\n");
      out.write("\t\tpadding:1.5%;\n");
      out.write("\t}\n");
      out.write("\t.title{\n");
      out.write("\t\tborder-bottom-style: inset;\n");
      out.write("\t    padding: 5px;\n");
      out.write("\t    margin-bottom: 10px;\n");
      out.write("\t}\n");
      out.write("\t.login{\n");
      out.write("\t\tfont-size:12px;\n");
      out.write("\t}\n");
      out.write("\t.intro{\n");
      out.write("\t\tfont-size:13px;\n");
      out.write("\t}\n");
      out.write("\t.xiangqing{\n");
      out.write("\t\tpadding-top:30px;\n");
      out.write("\t\ttext-align:center;\n");
      out.write("\t}\n");
      out.write("\t</style>\n");
      out.write("\t<div style=\"padding-top:50px; \" class=\"sanhoutai\">\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"title\">网站管理后台</div>\n");
      out.write("\t\t\t<div class=\"login\">\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t登陆地址：\n");
      out.write("\t\t\t\t\t<a href=\"../login.do\" target=\"_black\">");
      out.print(Global.get("MASTER_SITE_URL") );
      out.write("login.do</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div>登陆账号： <b>wangzhan</b></div>\n");
      out.write("\t\t\t\t<div>登陆密码： <b>wangzhan</b></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"intro\">\n");
      out.write("\t\t\t\t网站管理后台，是专门针对网站进行修改、操作的后台。<br/>\n");
      out.write("\t\t\t\t客户可以通过开通的账号跟密码，自己登陆网站管理后台，进行管理网站。比如发布新闻信息、产品信息、查看网站访问统计等。\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"xiangqing\">\n");
      out.write("\t\t\t\t<a href=\"http://help.wscso.com/5732.html\" class=\"layui-btn layui-btn-primary\" target=\"_black\">查看详细说明</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"title\">代理后台</div>\n");
      out.write("\t\t\t<div class=\"login\">\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t登陆地址：\n");
      out.write("\t\t\t\t\t<a href=\"../login.do\" target=\"_black\">");
      out.print(Global.get("MASTER_SITE_URL") );
      out.write("login.do</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div>登陆账号： <b>agency</b></div>\n");
      out.write("\t\t\t\t<div>登陆密码： <b>agency</b></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"intro\">\n");
      out.write("\t\t\t\t开通网站、开通下级代理，都是通过代理后台来开通的。\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"xiangqing\">\n");
      out.write("\t\t\t\t<a href=\"http://help.wscso.com/5717.html\" class=\"layui-btn layui-btn-primary\" target=\"_black\">查看详细说明</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"title\">总管理后台</div>\n");
      out.write("\t\t\t<div class=\"login\">\n");
      out.write("\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t登陆地址：\n");
      out.write("\t\t\t\t\t<a href=\"../login.do\" target=\"_black\">");
      out.print(Global.get("MASTER_SITE_URL") );
      out.write("login.do</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div>登陆账号： <b>admin</b></div>\n");
      out.write("\t\t\t\t<div>登陆密码： <b>admin</b></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"intro\">\n");
      out.write("\t\t\t\t总管理后台，只是提供查看审核的作用。如查看统计信息、审核所有网站内有没有发布违法违规的文章等。\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"xiangqing\">\n");
      out.write("\t\t\t\t<a href=\"http://help.wscso.com/5716.html\" class=\"layui-btn layui-btn-primary\" target=\"_black\">查看详细说明</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<div style=\" position: absolute; bottom: 20px; text-align: center;width: 100%;\">\n");
      out.write("\t\t提示：网站做好后，请去自行将这三个密码改掉！\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../iw/common/foot.jsp", out, false);
      out.write(' ');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
