/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2019-01-24 01:04:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.site;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.xnx3.net.MailUtil;
import com.xnx3.wangmarket.domain.G;
import com.xnx3.wangmarket.admin.entity.Site;
import com.xnx3.j2ee.Global;

public final class baseSet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1430113524000L));
    _jspx_dependants.put("/WEB-INF/lib/xnx3_tld.jar", Long.valueOf(1512734430000L));
    _jspx_dependants.put("jar:file:/E:/Work/yunjianzan/Tomcat8.5/webapps/ROOT/WEB-INF/lib/xnx3_tld.jar!/META-INF/xnx3.tld", Long.valueOf(1495004768000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.xnx3.wangmarket.domain.G");
    _jspx_imports_classes.add("com.xnx3.j2ee.Global");
    _jspx_imports_classes.add("com.xnx3.net.MailUtil");
    _jspx_imports_classes.add("com.xnx3.wangmarket.admin.entity.Site");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../iw/common/head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("网站基本设置", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("\n");
      out.write("<body style=\"text-align:left; min-width:10px;\">\n");
      out.write("<div class=\"weui_cells weui_cells_access\" style=\"margin-top: 0em;\">\n");
      out.write("\t<a class=\"weui_cell\" href=\"javascript:updateTitle();\">\n");
      out.write("\t\t<div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("\t\t\t<p>网站标题</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"weui_cell_ft\" id=\"nameDiv\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t</a>\n");
      out.write("\t<a class=\"weui_cell\" href=\"javascript:updateDomain_info();\">\n");
      out.write("\t\t<div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("\t\t\t<p>分配域名</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"weui_cell_ft\" id=\"domainInput\">\n");
      out.write("\t\t\t<span style=\"float: left;\">\n");
      out.write("\t\t\t\t<div id=\"domainInput_wangmarket\">http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.domain }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('.');
      out.print(G.getAutoAssignMainDomain() );
      out.write("</div>\n");
      out.write("\t\t\t</span>\n");
      out.write("\t\t</div>\n");
      out.write("\t</a>\n");
      out.write("\t<a class=\"weui_cell\" href=\"javascript:updateBindDomain_info();\">\n");
      out.write("\t\t<div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("\t\t\t<p>绑定域名</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"weui_cell_ft\" id=\"domainInput\">\n");
      out.write("\t\t\t<span style=\"float: left;\">\n");
      out.write("\t\t\t\t<div id=\"domainInput_bind\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.bindDomain }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t</span>\n");
      out.write("\t\t</div>\n");
      out.write("\t</a>\n");
      out.write("\t<a class=\"weui_cell\" href=\"javascript:updateDiBuLianXi();\">\n");
      out.write("\t\t<div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("\t\t\t<p>联系人姓名</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"weui_cell_ft\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t</a>\n");
      out.write("\t<a class=\"weui_cell\" href=\"javascript:updateDiBuLianXi();\">\n");
      out.write("\t\t<div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("\t\t\t<p>联系电话</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"weui_cell_ft\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t</a>\n");
      out.write("\t<a class=\"weui_cell\" href=\"javascript:updateDiBuLianXi();\">\n");
      out.write("\t\t<div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("\t\t\t<p>联系QQ</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"weui_cell_ft\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.qq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t</a>\n");
      out.write("\t<a class=\"weui_cell\" href=\"javascript:updateDiBuLianXi();\">\n");
      out.write("\t\t<div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("\t\t\t<p>公司(团体)名</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"weui_cell_ft\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.companyName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t</a>\n");
      out.write("\t<a class=\"weui_cell\" href=\"javascript:updateDiBuLianXi();\">\n");
      out.write("\t\t<div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("\t\t\t<p>办公地址</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"weui_cell_ft\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.address }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t</a>\n");
      out.write("\t\n");
      out.write("\t");
 //判断是否已开启邮件发送功能
		if(MailUtil.username != null && MailUtil.username.length() > 0 || MailUtil.password != null && MailUtil.password.length() > 0){
	
      out.write("\n");
      out.write("\t\t<a class=\"weui_cell\" href=\"javascript:;\">\n");
      out.write("\t\t\t<div class=\"weui_cell_bd weui_cell_primary\">\n");
      out.write("\t\t\t\t<p>我的邮箱</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"weui_cell_ft\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t</a>\n");
      out.write("\t");
 } 
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("//自适应弹出层大小\n");
      out.write("var index = parent.layer.getFrameIndex(window.name); //获取窗口索引\n");
      out.write("parent.layer.iframeAuto(index);\n");
      out.write("\n");
      out.write("//改网站名字\n");
      out.write("function updateTitle(){\n");
      out.write("\tparent.layer.close(index);\n");
      out.write("\t//window.parent.siteNameClick();\n");
      out.write("\tparent.updateSiteName();\n");
      out.write("}\n");
      out.write("\n");
      out.write("//更改网站二级域名\n");
      out.write("function updateDomain_info(){\n");
      out.write("\tparent.layer.close(index);\n");
      out.write("\tparent.$('#subWindowsParam').text('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.domain }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("\tparent.updateDomain();\n");
      out.write("}\n");
      out.write("\n");
      out.write("//更改网站自己绑定的域名\n");
      out.write("function updateBindDomain_info(){\n");
      out.write("\t//parent.layer.close(index);\n");
      out.write("\t//parent.$('#subWindowsParam').text('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.bindDomain }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("\tparent.updateBindDomain();\n");
      out.write("}\n");
      out.write("\n");
      out.write("//更改网站的相关联系信息\n");
      out.write("function updateDiBuLianXi(){\n");
      out.write("\tparent.layer.close(index);\n");
      out.write("\tparent.updateFooterSiteInfo();\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
